{
    generate = [
        psi = 'yes'
    ]
    psiClassPrefix="Lean4"
    psiImplClassSuffix="Impl"
    psiPackage="lean4ij.language"
    psiImplPackage="lean4ij.language"

    parserClass = "lean4ij.language.Lean4Parser"

    elementTypeHolderClass = "lean4ij.language.psi.TokenType"
    tokenTypeClass = "lean4ij.language.Lean4TokenType"
    elementTypeClass = "lean4ij.language.Lean4TokenType"
}

tokens ::= (
    LINE_COMMENT|
    // WHITE_SPACE is context sensitive in lean4 and hence we will not use the default
    // com.intellij.psi.TokenType.WHITE_SPACE which is ignored by the lexer
    // but define our own
    // Originally this comes from the need for hovering over the white space to show
    // the documentation and content range
    WHITE_SPACE|
    STRING|
    KEYWORD_COMMAND1|
    KEYWORD_COMMAND_PREFIX|
    KEYWORD_MODIFIER|
    KEYWORD_COMMAND2|
    KEYWORD_COMMAND3|
    IDENTIFIER|
    LEFT_PAREN|
    RIGHT_PAREN|
    LEFT_BRACKET|
    RIGHT_BRACKET|
    LEFT_BRACE|
    RIGHT_BRACE|
    LEFT_UNI_BRACKET|
    RIGHT_UNI_BRACKET|
    DOT|
    MISC_COMPARISON_SYM|
    MISC_PLUS_SYM|
    MISC_MULTIPLY_SYM|
    MISC_EXPONENT_SYM|
    MISC_ARROW_SYM|
    OTHER|
    DOC_COMMENT|
    BLOCK_COMMENT|
    AT|
    COLON|
    MISC_COMPARISON_SYM|
    STAR|
    KEYWORD_COMMAND5|
    KEYWORD_COMMAND6|
    DEFAULT_TYPE|
    FOR_ALL|COMMA|EQUAL|
    NUMBER|NEGATIVE_NUMBER|
    KEYWORD_SORRY|
    TEMPLATE_TRIGGER|
    ASSIGN|
    PLACEHOLDER|
    definition|
    attributes
    )*

// here because adding whitespace now, we must change this too for compatible
definition ::= KEYWORD_COMMAND4 (WHITE_SPACE)* ((IDENTIFIER DOT)*IDENTIFIER)?
// TODO maybe finer structure for this
// Fix https://github.com/onriv/lean4ij/issues/106 with STRING
attributes ::= ATTRIBUTE_START (WHITE_SPACE)* (IDENTIFIER|LEFT_PAREN|RIGHT_PAREN|ASSIGN|WHITE_SPACE|STRING)* RIGHT_BRACKET|
    ATTRIBUTE (WHITE_SPACE)+ LEFT_BRACKET (IDENTIFIER|LEFT_PAREN|RIGHT_PAREN|ASSIGN|WHITE_SPACE|STRING)* RIGHT_BRACKET