{
    generate = [
        psi = 'no'
    ]

    parserClass = "lean4ij.language.Lean4Parser"

    elementTypeHolderClass = "lean4ij.language.psi.TokenType"
    tokenTypeClass = "lean4ij.language.Lean4TokenType"
}

tokens ::= (WHITE_SPACE|LINE_COMMENT|STRING|KEYWORD_COMMAND1|KEYWORD_COMMAND_PREFIX|KEYWORD_MODIFIER|KEYWORD_COMMAND2|KEYWORD_COMMAND3|IDENTIFIER|LEFT_PAREN|RIGHT_PAREN|LEFT_BRACKET|RIGHT_BRACKET|LEFT_BRACE|RIGHT_BRACE|LEFT_UNI_BRACKET|RIGHT_UNI_BRACKET|DOT|MISC_COMPARISON_SYM|MISC_PLUS_SYM|MISC_MULTIPLY_SYM|MISC_EXPONENT_SYM|MISC_ARROW_SYM|OTHER|DOC_COMMENT|BLOCK_COMMENT)*
